const API_BASE_URL = 'http://localhost:3001'; // Assuming json-server is running on port 3001

/**
 * @typedef {object} GeneralLedgerAccount
 * @property {string} id - Unique identifier (typically auto-generated by json-server or backend)
 * @property {string} accountNumber - G/L Account Number (e.g., '10100-000-00')
 * @property {string} description - Account Description
 * @property {string} recordType - Record Type (e.g., 'S' for Sub, 'M' for Main)
 * @property {string} rollupCode - Roll-up Code
 * @property {string} periodValidation - Period Validation flag (e.g., 'Y'/'N')
 * @property {string} normalBalance - Normal Balance (e.g., 'D' for Debit, 'C' for Credit)
 * @property {string} accountCategory - Account Category (e.g., 'AS', 'LI', 'EQ', 'IN', 'EX')
 * @property {string} accountStatus - Account Status (e.g., 'A' for Active, 'I' for Inactive)
 * @property {string} reportGroup - Account Report Group
 * @property {string} historyFlag - History Flag (e.g., 'Y'/'N')
 * @property {string} consolidationFlag - Consolidation Flag (e.g., 'Y'/'N')
 * @property {string} intercompanyFlag - Intercompany Account Flag (e.g., 'Y'/'N')
 * @property {string} allocationFlag - Allocation Flag (e.g., 'Y'/'N')
 * @property {string} fasbGroup - FASB Group
 * @property {string} unitsRequiredFlag - Units Required Flag (e.g., 'Y'/'N')
 * @property {string} lastActivityDate - Last Activity Date (e.g., 'MMDDYY')
 * @property {string} changedByOperator - Operator ID who last changed the record
 * @property {string} lastChangeDate - Date of last change (6 characters, date format YYMMDD)
 */

/**
 * Fetches all General Ledger accounts.
 * @returns {Promise<GeneralLedgerAccount[]>}
 */
export const getGeneralLedgerAccounts = async () => {
  const response = await fetch(`${API_BASE_URL}/generalLedgerAccounts`);
  if (!response.ok) {
    throw new Error('Failed to fetch General Ledger accounts');
  }
  return response.json();
};

/**
 * Adds a new General Ledger account.
 * @param {Omit<GeneralLedgerAccount, 'id'>} accountData - The data for the new account.
 * @returns {Promise<GeneralLedgerAccount>} The newly created account with its ID.
 */
export const addGeneralLedgerAccount = async (accountData) => {
  const response = await fetch(`${API_BASE_URL}/generalLedgerAccounts`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(accountData),
  });
  if (!response.ok) {
    throw new Error('Failed to add General Ledger account');
  }
  return response.json();
};

/**
 * Updates an existing General Ledger account.
 * @param {string | number} accountId - The ID of the account to update.
 * @param {Partial<GeneralLedgerAccount>} accountData - The data to update for the account.
 * @returns {Promise<GeneralLedgerAccount>} The updated account.
 */
export const updateGeneralLedgerAccount = async (accountId, accountData) => {
  const response = await fetch(`${API_BASE_URL}/generalLedgerAccounts/${accountId}`, {
    method: 'PUT',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(accountData),
  });
  if (!response.ok) {
    throw new Error('Failed to update General Ledger account');
  }
  return response.json();
};

/**
 * Deletes a General Ledger account.
 * @param {string | number} accountId - The ID of the account to delete.
 * @returns {Promise<void>} A promise that resolves when the deletion is successful.
 */
export const deleteGeneralLedgerAccount = async (accountId) => {
  const response = await fetch(`${API_BASE_URL}/generalLedgerAccounts/${accountId}`, {
    method: 'DELETE',
  });
  if (!response.ok) {
    // json-server returns an empty object {} on successful DELETE, which is fine.
    // It might return errors for other reasons though.
    throw new Error('Failed to delete General Ledger account');
  }
  // No content is usually returned on successful DELETE, so no .json() call
  return;
};
